package ma.aza.sgtm.logistics.config;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.info.Contact;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.License;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import io.swagger.v3.oas.annotations.servers.Server;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.ExternalDocumentation;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@SecurityScheme(
        name = "bearerAuth",
        type = SecuritySchemeType.HTTP,
        scheme = "bearer",
        bearerFormat = "JWT",
        description = "JWT token generated by /auth/login"
)
@OpenAPIDefinition(
        info = @Info(
                title = "SGTM Logistics API",
                version = "v1",
                description = "API surface for managing vehicles, day reports, construction sites and GPS integrations.",
                contact = @Contact(name = "SGTM Logistics"),
                license = @License(name = "Proprietary")
        ),
        security = {@SecurityRequirement(name = "bearerAuth")},
        servers = {@Server(url = "/", description = "Default server")}
)
public class OpenApiConfig {

    @Bean
    public OpenAPI baseOpenAPI() {
        return new OpenAPI()
                .externalDocs(new ExternalDocumentation()
                        .description("Project repository")
                        .url("https://gitlab.aza.ma/sgtm/sgtm-logistics"));
    }
}
